// apps/fe-wtc-tech-test-angularv2/src/app/app.component.ts
import { Component } from '@angular/core';
import LINKS from '../../../../common/links.json';
const { Instructions, Swagger, Design } = LINKS;

@Component({
  selector: 'mono-nx-test-with-nextjs-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'fe-wtc-tech-test-angularv2';
  links = [Instructions, Swagger, Design].map((value) => value);
  logo = '../assets/testflix_logo.png';
}

<header class="header">
  <img src="{{ logo }}" alt="testflix logo" height="130px" />
</header>
<main class="container">
  <mono-nx-test-with-nextjs-movies-list></mono-nx-test-with-nextjs-movies-list>
</main>
<footer class="footer">
  <div *ngFor="let link of links">
    <a class="button" tabindex="0" aria-disabled="false" href="{{ link.href }}"
      ><span class="MuiButton-label">{{ link.text }}</span></a
    >
  </div>
</footer>

<router-outlet></router-outlet>

// apps/fe-wtc-tech-test/pages/_app.tsx
import React from 'react';
import { Container, CssBaseline } from '@material-ui/core';
import { Header, Theme } from '@mono-nx-test-with-nextjs/fe-wtc-tech-test';
import { Footer } from '@mono-nx-test-with-nextjs/ui';
import LINKS from '../../../common/links.json';
import { ThemeProvider } from '@material-ui/core/styles';
import { makeStyles, createStyles } from '@material-ui/core/styles';

const { Instructions, Storybook, Design, Swagger } = LINKS;

const useStyles = makeStyles(() =>
  createStyles({
    contentContainer: {
      padding: '0 27px',
    },
    root: {
      padding: '0',
    },
  })
);

const App = ({ Component, pageProps }) => {
  const classes = useStyles();
  return (
    <ThemeProvider theme={Theme}>
      <CssBaseline />
      <Container className={classes.root}>
        <Header />
        <div className={classes.contentContainer}>
          <Component {...pageProps} />
        </div>
        <Footer links={[Instructions, Design, Swagger, Storybook]} />
      </Container>
    </ThemeProvider>
  );
};

export default App;
